name: Build and Publish Python Package to PyPI

on:
  push:
    tags: ['python-v[0-9].[0-9]+.[0-9]+']

jobs:
  build:
    name: Build with SetupTools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Create a Python virtual environment
        run: |
          python -m venv env
          source env/bin/activate
        working-directory: sdk/python

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/python-v}" >> $GITHUB_ENV

      - name: Install build dependencies
        run: |
          source env/bin/activate
          python -m pip install build
        working-directory: sdk/python

      - name: Build distributions into dist folder
        shell: bash -l {0}
        run: |
          source env/bin/activate
          python -m build
        working-directory: sdk/python
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ env.VERSION }}
  
      - name: List files in the dist folder
        run: |
          echo "Release version number is: $VERSION"
          ls ${{ github.workspace }}/sdk/python/dist

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: sdk/python/dist

  pypi-publish:
    name: Upload Release to PyPI
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: pypi
      url: https://pypi.org/p/freewayai
    permissions:
      id-token: write

    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist

      - name: List files in the dist folder
        run: |
          ls ${{ github.workspace }}/dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
